icons = "awesome"
theme = "solarized-dark"

[[block]]
block = "net"
device = "enp1s0"
speed_up = false
speed_down = false

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60 
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home/willy"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "battery"
device = "BAT1"
interval = 10

[[block]]
block = "backlight"

[[block]]
block = "sound"
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
